name: 'build'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_pip:
    name: Linux pip
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 nbconvert[test]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test
      run: |
        flake8 *.py submissions/*/*.py
        python download_data.py
        ramp-test --quick-test
